### ISSUE TITLE
Support for Linkding

### ISSUE THREAD

**Issue by rounakdatta** [fibelatti/pinboard-kotlin#107]
While Pinboard is lovely and it's good to support a longstanding privacy-centric app, there's also a close OSS competitor of Pinboard: [Linkding](https://github.com/sissbruecker/linkding).

I'm wondering can Pinkt be used with Linkding - given there are two versions of Pinboard APIs (and Linkding uses v2). If not, what would be the effort required to get it working?

**Comment by fibelatti** [comment]
Hi @rounakdatta, thanks for reaching out. It's the first time I hear about Linkding and it sounds really interesting!

After taking a quick glance at it I would say that the Pinkt UI is very much compatible, although a few adjustments would be needed. Regarding the effort for that, I'll answer it roughly as I still have a couple open questions about Linkding which I need to explore further to answer.

- Linkding seems to be distributed, so the Pinkt authentication needs to be updated to accept your Linkding instance URL
- The REST API definition is slightly different, but this can be easily achieved with another implementation of the [repository](https://github.com/fibelatti/pinboard-kotlin/blob/main/app/src/main/kotlin/com/fibelatti/pinboard/features/posts/domain/PostsRepository.kt) backed up by the Linkding API
- Linkding supports bulk editing which Pinboard still doesn't support, so Pinkt doesn't support it either
- Linkding doesn't have notes, so that needs to be hidden on the menu

Time allowing I'll explore this new integration in the near future, thanks for bringing it up to my attention! I'll keep this issue open so that I can post any updates here

**Comment by fibelatti** [comment]
Hi @rounakdatta @dahamsta @ecogit and @qcasey!

Thank you so much for your interest in this integration and your patience so far. Life and work have kept me busy in the first half of the year, but I'm happy to tell you that I've finally started working on it. Check out this quick demo I put together:

https://github.com/fibelatti/pinboard-kotlin/assets/3277516/d7899b92-77c9-4181-8081-ca3bd52c5f97

Most of the app features will be available when using Pinkt for Linkding since there's a great overlap between it and Pinboard but as I anticipated there are a few things which will be unavailable, such as:

- Notes, which has no equivalent in Linkding
- Popular bookmarks, which also doesn't have an equivalent
- Sharing a URL with applied filters

I can't promise an exact release date yet, but here's what I've got left to do:

- Adding offline support and the same filtering capabilities. The data structure between the two services is slightly different so I cannot simply reuse
- Bookmark notes, since Pinboard only has title and description
- Archived bookmarks, plus archiving and unarchiving functionality

I'll keep you all informed of any further progress and developments.

**Comment by dahamsta** [comment]
Thanks for this, looking forward to trying it. FYI, Linkding has a notes field now:

https://github.com/sissbruecker/linkding/pull/472

**Comment by fibelatti** [comment]
> Thanks for this, looking forward to trying it. FYI, Linkding has a notes field now:
> 
> https://github.com/sissbruecker/linkding/pull/472

@dahamsta they are slightly different. Pinboard notes are independent from bookmarks, you can add, list and view them on their own, it's just a space to jot down anything you'd like. Linkding on the other hand has notes as an additional field on a bookmark.

When using Pinkt you will be able to access the corresponding feature of each platform.

**Comment by rounakdatta** [comment]
Super cool! Thanks for the work @fibelatti , let us know if we can help in any tiny way. Over the last year I've graduated from being a noob in Kotlin to somewhat okayish Kotliner :)

**Comment by fibelatti** [comment]
Thanks @rounakdatta! Once I get a working sample I'll likely open a testing group and your help will be much appreciated.

**Comment by ecogit** [comment]
> Most of the app features will be available when using Pinkt for Linkding since there's a great overlap between it and Pinboard but as I anticipated there are a few things which will be unavailable, such as:
> 
>     * Notes, which has no equivalent in Linkding
> 
>     * Popular bookmarks, which also doesn't have an equivalent
> 
>     * Sharing a URL with applied filters

Thank you @fibelatti for your profound evaluation and prototyping.

I just wanted to add that AFAIK Linkding is not yet supporting the functionality [Network](https://pinboard.in/network/) ([API_v2](https://idlewords.com/pinboard_api2_draft.htm#network). It's fruitful to subscribe to others with similar or inspiring interests in order to check their latest bookmarking activities. Btw, Network would be great to have in Pinkt as well ;p

**Comment by fibelatti** [comment]
@ecogit indeed Network is a very interesting feature but unfortunately until the Pinboard v2 API is released there's not way I'm able to add support to it

**Comment by ecogit** [comment]
@fibelatti   Ok, thank you for feedback.

Many downstream projects like yours seem to be waiting for Maciej Cegłowski to resurface and manage to complete it.

**Comment by fibelatti** [comment]
Hi @christianhans, @rounakdatta, @ecogit, @Operepadia, @qcasey and @smaradus! You have been tagged because you previously reacted positively to [this message](https://github.com/fibelatti/pinboard-kotlin/issues/107#issuecomment-1657216277) and I have great news.

It's been a long and winding road but I have finally integrated Linkding support onto the main branch and now I'm looking to test this before releasing it to the production channel. If you're familiar with installing unsigned APKs then you can head out to [this workflow run](https://github.com/fibelatti/pinboard-kotlin/actions/runs/9538592836). There you'll find an artifact, which is a zip file containing the APK built from source. Once you install you should be able to switch to Linkding and login to your instance.

In the meantime I'll be conducting my own tests to also ensure that the Pinboard integration continues to work as it should.

Thanks for your interest at this!

**Comment by fibelatti** [comment]
I spotted an issue where the APIs wouldn't switch correctly when trying to login to Linkding, it has been fixed and a new build is in progress: https://github.com/fibelatti/pinboard-kotlin/actions/runs/9538894557

The APK will be available as an artifact once it finished. Also, it's worth mentioning that for the time being archived bookmarks are not supported.

**Comment by OPerepadia** [comment]
Hi @fibelatti
Thanks for adding Linkding integration. I gave it a try, and noticed a few of issues with the search functionality. It seems to only search in the title, but not in the URL and description. And it doesn't seem to work with Cyrillic text.

But overall it works pretty well already. Thanks again!

**Comment by fibelatti** [comment]
@OPerepadia thanks for testing it! I'm gonna investigate why the search feature isn't working as it should, I had tested it and have automated tests in place as well but something must be off. I'll fix it before releasing the stable version.

Regarding the Cyrillic text, is the issue limited to search too or there's more to it?

**Comment by OPerepadia** [comment]
> Regarding the Cyrillic text, is the issue limited to search too or there's more to it?

Yes, it's only in search

**Comment by fibelatti** [comment]
@OPerepadia I found out what the issue was with search not working was. Linkding shows the website title and description by default if you leave them blank but I was not taking those into account when searching, only user entered title and description. That's fixed now, as well as enabling search within bookmark notes.

Unfortunately adding proper support for Cyrillic text requires a bit more work and I'll leave that for upcoming versions.

Once again thanks for testing and reporting the issue!

**Comment by fibelatti** [comment]
Hi @christianhans, @rounakdatta, @ecogit, @OPerepadia, @qcasey and @smaradus, I'm happy to announce that a version with support for linkding has been officially [launched](https://github.com/fibelatti/pinboard-kotlin/releases/tag/v3.0)! I've submitted it to the Play Store today so it should become available soon. It should also become available on IzzyOnDroid tomorrow once the next sweep happens.

I'm finally closing this issue. If you do have any feedback regarding this integration or anything else please feel free to submit a new issue.

Thanks for using the app!
