### ISSUE TITLE
Sharing intent interstitial: prompt for tags, description

### ISSUE THREAD

**Issue by dandv** [fibelatti/pinboard-kotlin#2]
Great to see an alternative for Pindroid! Thanks for putting in the work into this product, especially given the potentially uncertain future of Pinboard (no developments in a long while, author seemingly moved on to other projects).

I tag and summarize [my bookmarks](https://pinboard.in/u:dandv) (the last ones are blank because I saved them with Pinkt), and when saving, I would like to see the same behavior as the Pinboard bookmarklet: be prompted to tag and describe the bookmark.

**Comment by fibelatti** [comment]
Hey @dandv, thanks for the feedback and the suggestion. I had that in mind, or at least something similar to what Pocket does when you share links to it. I didn't do it at first because I wanted to get the app out, but I'll look into it again in the near future.

I'll also add an option to select default tags when sharing a link to Pinkt.

Also, you mentioned that you had an issue with your tags not syncing up properly. Is that still happening? Because if so I'd like to investigate that.

**Comment by fibelatti** [comment]
Implemented.
