### ISSUE TITLE
Links get shared to Pinboard before I've edited them

### ISSUE THREAD

**Issue by andrewducker** [fibelatti/pinboard-kotlin#4]
Hi,
Is there any way to have it not save to Pinboard before I've edited it and added the tags?

I'm auto-sharing on from Pinboard to other sites (Twitter, Facebook Page, etc) and I absolutely don't want it picking up an unedited version of the description.

**Comment by fibelatti** [comment]
Hi @andrewducker, sorry it took a while to respond. For the time being that's not an option. There's an option to open Pinkt immediately after sharing for further edits. I'll mark this issue as "enhancement" but it will be added to the backlog so that I can look into it in the future and see if it is possible.

**Comment by fibelatti** [comment]
@andrewducker Hi Andrew, this feature will finally be available in the next update (v1.14.0). Look for it in the preferences and you will have the option to edit your bookmarks before they are saved.

Thanks for the suggestion and for your patience while waiting for this feature.
