### ISSUE TITLE
Truncated description

### ISSUE THREAD

**Issue by dandv** [fibelatti/pinboard-kotlin#63]
When I view [this bookmark](https://pinboard.in/search/u:dandv?query=canned+food+wreck) in Pinkt, the description is truncated.

![image](https://user-images.githubusercontent.com/33569/180675634-b5898b9c-9387-4648-89dd-0566ca514ab8.png)

This would lead to data loss if the user edits something in the beginning of the description and saves without noticing the truncation.

**Comment by fibelatti** [comment]
@dandv this is now fixed in version 1.19.1 which should be available in the Play Store very soon. Thanks for reporting it!

**Comment by dandv** [comment]
Thanks, just wanted to check if the fix made it in 1.19.1 because that's what I'm using, and I still see truncation at about 2150 characters.

**Comment by fibelatti** [comment]
Hey @dandv, version 1.19.1 does contain the fix but Pinboard's REST API uses a `GET` for adding bookmarks rather than a `POST` or `PUT` as one would expect. Because of that, everything needs to be encoded into the URL as query parameters so if the description is too long the server will respond with `HTTP 414 URI Too Long`.

From my testing their server is configured to accept something in between 2000 and 3000 chars, so what I do in the app is use 3000 as the limit, subtract everything else (like the REST API url, bookmark url, title, etc.) and leave the remaining space to the bookmark ([relevant code if you're interested!](https://github.com/fibelatti/pinboard-kotlin/blob/main/app/src/main/kotlin/com/fibelatti/pinboard/features/posts/data/PostsDataSourcePinboardApi.kt#L99-L137)). It isn't great but it was the only way to avoid the issue.

The v2 of their REST API fixes this by using the proper verb but it isn't available yet and I'm not sure when it will be. In the meantime I'll probably add some explanation to the app to let users now that this can happen.

Thanks for keeping up with the issue and please don't hesitate to reach out again!
