### ISSUE TITLE
incorrect bookmark count

### ISSUE THREAD

**Issue by sridharrajs** [fibelatti/pinboard-kotlin#82]
The app shows a different bookmark count when you refresh the list. Please find the gif video of the issue attached.

![screen-20220908-063908](https://user-images.githubusercontent.com/1156953/189012221-0fb4bf02-2156-4ec2-bff5-48dfebe5049e.gif)

**Comment by fibelatti** [comment]
Hi @sridharrajs, thanks for reaching out!

In order to not overload the server with large queries and improve overall performance the app does paginated requests when fetching all bookmarks. It requests at most 5000 bookmarks at a time and while it does so it might show an "incorrect" count since there's no way of knowing how many bookmarks are there.

**Comment by sridharrajs** [comment]
Thanks for the context @fibelatti . Closing the issue.
