### ISSUE TITLE
Option to show more tags (or all tags)

### ISSUE THREAD

**Issue by danmichaelo** [fibelatti/pinboard-kotlin#9]
Thanks for making this app, it's great! The limitation that it shows max 3 tags per bookmark is a bit annoying though. I wish there was a setting, either (i) to change the value to some other value than 3, or (ii) to always show all tags, no matter how many.

**Comment by fibelatti** [comment]
Hi @danmichaelo, thanks for the feedback. I believe you're referring to the tags displayed in lists, right? If that's the case then it was made that way so that more bookmarks could be displayed each time but I understand how that can get in the way.

I'll look for a way of improving it, thanks for the suggestion.

**Comment by fibelatti** [comment]
Hi @danmichaelo, the next release (1.12.0) will display all tags in lists and not only the first three, I hope you enjoy. It will be available in the Play Store later today.

Thanks for your suggestion, kind regards.

**Comment by danmichaelo** [comment]
Wow, didn't expect it to get fixed and released so fast – that's fantastic, thanks a lot 👏🥳
