### ISSUE TITLE
Save to Pinboard from Share menu stopped working when App is closed

### ISSUE THREAD

**Issue by christianhans** [fibelatti/pinboard-kotlin#92]
First of all, thank you for making such a useful application!

Reproduce:

1. Close Pinkt
2. Share an URL via the Android share menu to Pinkt
3. Pinkt app will start but no save bookmark dialog appears 

This has worked previously, so I think it's a recent regression.

**Comment by fibelatti** [comment]
Hi @christianhans, thanks for reporting this issue! I noticed it as well but haven't been able to pinpoint the root cause yet since it's happening intermittently, hopefully your reproduction steps will assist me.

I'll release a patch for this as soon as it's fixed, apologies for any inconvenience this may be causing in the meantime.

**Comment by fibelatti** [comment]
Hi @christianhans, this issue is now [fixed](c51bcb61e3e9c49038fcd20b65ac197a37b622f7). I'll upload version 1.20.2 to the Play Store and it should become available soon enough.

Thanks for using the app! 🎉

**Comment by christianhans** [comment]
I can confirm the new version has fixed this bug. Thanks for the quick bugfix!
